package br.com.sisjupiter.auxiliar;

public class ColunasExcel {

	private String[] colunasDiagnostico = { 
			"ID_DIAGNOSTICO", "ID_COMUNIDADE", "COMUNIDADE", "DATA_DIAGNOS",
			"DATA_INSERT", "ID_EQUIPE", "EXECUTOR", "ID_USER", "SITUACAO_IMOVEL", "TIPO_CONTRUCAO", "TIPO_INSTALACAO",
			"RESIDENCIA", "COMERCIO", "INDUSTRIA", "PUBLICA", "USO_IMOVEL", "QTDE_CASAS", "TEMPO_OCUPACAO", "ATIVIDADE",
			"ENERGIA_ELETRICA", "ENERGIA_ELETRICA_IRREG", "INSTALACAO", "MEDIDOR", "PAVIMENTACAO", "COLETA_LIXO",
			"ABASTEC_AGUA", "ABASTEC_AGUA_IRREG", "HIDROMETRO", "DESTINO_ESGOTO", "CLIENTE", "CPF", "RG",
			"NACIONALIDADE", "UF_NASC", "MUN_NASC", "DTNASC", "SEXO", "TELRES", "TELCEL", "ESTADO_CIVIL", "EMAIL",
			"ENDERECO", "NUMATUAL", "NUMANTIGO", "COMPL", "BAIRRO", "MUN", "UF", "CEP", "QTDE_ADULTO", "QTDE_CRIANCA",
			"TEM_CONTA", "BANCO", "TEM_CARTAO_DEBITO", "RENDATOTAL", "COMPRO_FINANC", "TRANSP_CARRO_PROPRIO",
			"TRANSP_ONIBUS", "TRANSP_TREM", "TRANSP_METRO", "TRANSP_TAXI", "ACESSO_INTERNET", "WIFI", "3G",
			"QTDE_CARRO", "QTDE_MOTO", "QTDE_BICICLETA", "BENEF_BCPNUM", "BENEF_NISNUM", "TARIFA_SOCIAL",
			"BOLSA_FAMILIA", "BENEF_NOME", "BENEF_CPF", "BENEF_RG", "BENEF_SEXO", "BENEF_DTNASC", "BENEF_OBS",
			"60_ANOS_OU_MAIOR", "18_ANOS_OU_MENOR", "MENOR_1_ANO", "QTDE_DEF_VISUAL", "QTDE_DEF_AUDITIVO",
			"QTDE_DEF_FISICO", "QTDE_DEF_INTELECT", "QTDE_DEF_OUTROS", "TRATA_CANCER", "TRATA_TUBERCULOSE",
			"TRATA_HANSEN", "TRATA_ALIE_MENTAL", "TRATA_ESCLEROSE", "TRATA_PARALISIA", "TRATA_HEPATITE",
			"TRATA_CARDIACO", "TRATA_PARKINSON", "TRATA_RENAL", "TRATA_OUTRO", "TRAT_OUTRO_DESC", "MEMBRO_AMEBIASE",
			"MEMBRO_AMEBIASE_PARENT", "MEMBRO_GASTRO", "MEMBRO_GASTRO_PARENT", "MEMBRO_GIARDIASE",
			"MEMBRO_GIARDIASE_PARENT", "MEMBRO_FEBRE_TIFOIDE", "MEMBRO_FEBRE_TIFOIDE_PARENT", "MEMBRO_HEPATITE",
			"MEMBRO_HEPATITE_PARENT", "MEMBRO_COLERA", "MEMBRO_COLERA_PARENT", "MEMBRO_ESQUITOSSO",
			"MEMBRO_ESQUITOSSO_PARENT", "MEMBRO_ASCARIDIASE", "MEMBRO_ASCARIDIASE_PARENT", "MEMBRO_TENIASE",
			"MEMBRO_TENIASE_PARENT", "MEMBRO_LEPTOSPIROSE", "MEMBRO_LEPTOSPIROSE_PARENT", "MEMBRO_MALARIA",
			"MEMBRO_MALARIA_PARENT", "MEMBRO_DENGUE", "MEMBRO_DENGUE_PARENT", "MEMBRO_FEBREAMAR",
			"MEMBRO_FEBREAMAR_PARENT", "MEMBRO_CHIKUNG", "MEMBRO_CHIKUNG_PARENT", "MEMBRO_ZICAVIRUS",
			"MEMBRO_ZICAVIRUS_PARENT", "MEMBRO_CIANOBACTER", "MEMBRO_CIANOBACTER_PARENT", "VAL_DOACAO", "VAL_APOSENT",
			"VAL_PENSAO_ALIMEN", "VAL_SEG_DESEMPR", "VAL_EMPR_INFORMAL", "VAL_EMPR_FORMAL", "VAL_BOLSA_FAMIL",
			"VAL_OUTRO", "VAL_OUTR_DESCR", "GRAU_ESCOLAR", "GRAU_ESCOLAR_COMPL", "SABE_ESCREVER", "SABE_LER",
			"PROFISSAO_RESP_FAMILIA", "NEGOCIACAO_DEB_ENERGIA", "VALOR_PARCELA_ENERG", "QTDE_PARCELA_ENERG",
			"VENC_PARCELA_ENERG", "NEGOCIACAO_DEB_AGUA", "VALOR_PARCELA_AGUA", "QTDE_PARCELA_AGUA", "VENC_PARCELA_AGUA",
			"CONHEC_OBRA_SANEAM", "BENEF_SANEA_PREV_DOENCA", "BENEF_SANEA_FORTAL_ECONO", "BENEF_SANEA_VALORI_IMOB",
			"BENEF_SANEA_VALOR_TURISM", "OBS_GERAIS", "MORADORES", "RESP_CASA_NOME1", "RESP_CASA_TEL1",
			"RESP_CASA_NOME2", "RESP_CASA_TEL2", "VIZINHO_NOME1", "VIZINHO_TEL1", "VIZINHO_NOME2", "VIZINHO_TEL2",
			"CONTATO_ALTERN_NOME1", "CONTATO_ALTERN_TEL1", "CONTATO_ALTERN_NOME2", "CONTATO_ALTERN_TEL2",
			"CONTATO_PROF_NOME1", "CONTATO_PROF_TE1", "CONTATO_PROF_NOME2", "CONTATO_PROF_TE2", "EQUIP_PUBLICO",
			"RELACAOVIZ", "REL_RECOR_VIZINHO", "REL_RECOR_VIZINHO_FREQ", "CONSIDERACOES_FAMILIAS_AO_REDOR",
			"HOSPITAL_NOME", "REF_NOME", "COORDX", "COORDY", "COORDXDIAG", "COORDYDIAG" 
			};

	
	public String[] getColunasDiagnostico() {
		return colunasDiagnostico;
	}

	public void setColunasDiagnostico(String[] colunasDiagnostico) {
		this.colunasDiagnostico = colunasDiagnostico;
	}
	
	
}
